package second_semester;

public class Chap_10_prac_10_06 {

	public static void main(String[] args) {
		int[] array = {0, 1, 2};
		try {
			int x = array[3];
		} catch(Exception e) {
			System.out.println("어이쿠!");
		} catch(ArrayIndexOutOfBoundsException e) { // 이미 exception e 에서 모든오류를 처리하므로 밑 오류처리까지 도달하지못해 오류가 발생한다.
			System.out.println("원소가 존재하지 않습니다.");
		}
		System.out.println("종료");

	}

}
